#!/bin/sh
#### Cluster specific arguments ####

#SBATCH --job-name=NF_MUM
#SBATCH --output=logs/nf_%j.out
#SBATCH --error=err
#SBATCH --partition=EPYC
#SBATCH --nodes=1
#SBATCH --ntasks=23
#SBATCH --cpus-per-task=1
#SBATCH --mem=64G
#SBATCH --time=24:00:00

module load singularity/3.10.4
module load java/1.8.0
module load R/4.2.3

evoverse=/orfeo/LTS/LADE/LT_storage/lvaleriani/nextflow_modules
RESULTS_PATH=$evoverse/results


/orfeo/LTS/CDSLab/LT_storage/ncalonaci/nextflow run $evoverse/main.nf \
 -c $evoverse/modules/config/nextflow_config_slurm \
 --samples $evoverse/input.csv \
 --publish_dir $RESULTS_PATH

