#!/bin/sh
#### Cluster specific arguments ####

#SBATCH --job-name=NF_MUM
##SBATCH --output=logs
#SBATCH --error=err
#SBATCH --partition=EPYC
#SBATCH --nodes=1
#SBATCH --ntasks=23
#SBATCH --cpus-per-task=1
#SBATCH --mem=64G
#SBATCH --time=12:00:00
#SBATCH --account=cdslab
#
#
module load singularity/3.10.4
module load java/1.8.0
module load R/4.2.3

##REPO_PATH="/u/cdslab/ebusca00/scratch/GitHub/nextflow_modules"
##RESULTS_PATH="/u/cdslab/ebusca00/scratch/nextflow_runs/results/"

REPO_PATH="/u/cdslab/ggandolfi/scratch/nextflow_modules"
RESULTS_PATH="/orfeo/cephfs/scratch/cdslab/ggandolfi/nextflow_results" 
#RESULTS_PATH="/u/cdslab/ggandolfi/scratch/nextflow_modules_fork/results/"

/orfeo/LTS/CDSLab/LT_storage/ncalonaci/nextflow/nextflow run $REPO_PATH/main.nf \
    -c $REPO_PATH/modules/config/nextflow_config_slurm \
    --samples $REPO_PATH/sample_input.csv --publish_dir $RESULTS_PATH --tools "viber" \
    --mode "singlesample"

